version: '3'
services:
  maplestory:
    build: .
    depends_on:
      - db
      - prometheus
      - grafana
    ports:
      # Login server
      - "8484:8484"
      # Channels.
      # Format: WWCC, where WW is 75 plus the world number and CC is 75 plus the channel number (both zero indexed).
      # In this case, world 1 channels 1-3.
      - "7575-7577:7575-7577"
    volumes:
      # Config changes can be reloaded without rebuilding the image.
      # Still requires a redeployment as they're sourced on startup.
      - ./config.yaml:/opt/server/config.yaml
      - ./scripts:/opt/server/scripts
      - ./wz:/opt/server/wz
    environment:
      DB_HOST: "db"
      JAVA_OPTS: "$JAVA_OPTS -javaagent:/jmx_exporter/jmx_prometheus_javaagent-0.13.0.jar=19080:/jmx_exporter/tomcat.yaml"
  db:
    image: mysql:8.0.23
    ports:
      - "3306:3306"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
      MYSQL_DATABASE: "cosmic"
      MYSQL_USER: "cosmic_server"
      MYSQL_PASSWORD: "snailshell"
    volumes:
      - ./database/docker-db-data:/var/lib/mysql
      - ./database/sql:/docker-entrypoint-initdb.d

    prometheus:
      image: prom/prometheus:master
      restart: unless-stopped
      volumes:
        - ./docker/prometheus.yml:/etc/prometheus/prometheus.yml
      ports:
        - 9090:9090

    grafana:
      image: grafana/grafana:6.7.3
      restart: unless-stopped
      # environment:
      #     GF_INSTALL_PLUGINS: ""
      ports:
        - 3000:3000